export const initiatives = [
  {
    tamilName: "Data என்ன சொல்லுது",
    englishName: "System Transparency",
    description: "Track and celebrate chapter performance with full data visibility. Every referral, every rupee — measured and shared.",
    slug: "data-transparency",
    icon: "📊",
    fullDescription: [
      "In BNI Miracles, we believe that what gets measured gets managed. Data என்ன சொல்லுது is our commitment to full transparency in chapter performance — making every metric visible to every member.",
      "From weekly referral counts to thankyou-for-closed-business (TYFCB) totals, every number is tracked, visualised, and discussed openly. This creates a culture of accountability where every member can see their contribution and the collective impact of the chapter.",
      "We celebrate wins — big and small. A member who passed their first referral is celebrated as much as the one who generated a crore in business. The data doesn't judge; it motivates.",
      "This initiative also helps the chapter leadership identify where support is needed, which business categories are active, and how the chapter's referral economy is growing month over month.",
    ],
  },
  {
    tamilName: "Phone-a எடு Referral-a பிடி",
    englishName: "Referral Drive",
    description: "Pick up the phone, pass a referral. A focused drive to multiply referrals within and beyond the chapter.",
    slug: "referral-drive",
    icon: "📞",
    fullDescription: [
      "The simplest BNI advice is also the most powerful: pick up the phone. Phone-a எடு Referral-a பிடி is a structured initiative that challenges every member to actively make calls and generate referrals.",
      "During a referral drive week, members commit to calling at least three people in their network and identifying one referral opportunity per call. The energy in the chapter meeting room is electric when referral counts spike.",
      "This initiative breaks the habit of passive networking. Instead of waiting for referrals to come to you, you actively seek them out. It reinforces the BNI philosophy that givers gain — the more you give, the more you receive.",
      "Past drives have resulted in 2x-3x the normal weekly referral count, directly translating into thousands of rupees in new business for members. The initiative runs periodically and is always a chapter highlight.",
    ],
  },
  {
    tamilName: "Vanakam தல! (Meet your Head Table)",
    englishName: "Leadership Connect",
    description: "Open, informal sessions where members connect with chapter leadership. No agenda, just conversation.",
    slug: "meet-head-table",
    icon: "🤝",
    fullDescription: [
      "Leadership should never feel distant. Vanakam தல! is an open-door initiative where any member can sit down informally with the chapter's Head Table — President, Vice President, Secretary Treasurer, and other leadership roles.",
      "These sessions have no agenda. Members can ask questions, share ideas, voice concerns, or simply get to know the people leading the chapter. The Head Table members are also regular business owners, and these conversations often spark unexpected referrals and collaborations.",
      "We run these sessions at coffee shops, member offices, or virtually — wherever is convenient. The goal is to remove hierarchy and make leadership approachable.",
      "Members who attend Vanakam தல! sessions consistently report feeling more connected to the chapter, more motivated to participate, and more likely to bring visitors. It's a small initiative with an outsized impact on chapter culture.",
    ],
  },
  {
    tamilName: "கொஞ்சம் Relax Mame!",
    englishName: "Socials & Offsite",
    description: "Unofficial member meetups at beach resorts, cafés, and fun venues. Business relationships built over relaxed moments.",
    slug: "socials",
    icon: "🌴",
    fullDescription: [
      "Not every great business relationship is built in a formal meeting room. கொஞ்சம் Relax Mame! is our acknowledgment that the best connections often happen when people let their guard down.",
      "We organise informal gatherings at beach resorts outside Chennai, rooftop cafés, gaming zones, and other fun venues. There is no agenda, no presentations, no structured networking — just members being themselves.",
      "These events have produced some of the strongest member bonds in the chapter. When you've laughed with someone over a game of carrom or watched the sunset together at a beach, the business relationship that follows is built on genuine trust.",
      "Events are member-led and organic — anyone can propose a outing. The chapter subsidises or co-sponsors select events to ensure maximum participation. Spouses and families are sometimes invited to truly celebrate the community we're building.",
    ],
  },
  {
    tamilName: "கலப்பு 121 படலம்",
    englishName: "Cross-Chapter 121 Conclave",
    description: "A conclave where members from multiple BNI chapters meet for one-to-ones, expanding referral networks across chapters.",
    slug: "cross-chapter-121",
    icon: "🌐",
    fullDescription: [
      "Your referral network shouldn't stop at your chapter boundary. கலப்பு 121 படலம் is a structured conclave that brings together members from BNI Miracles and partner chapters across Chennai for intensive one-to-one meetings.",
      "In a typical session, 40-80 members from 3-5 chapters spend a day rotating through structured 10-minute one-to-ones. By the end, every participant has met 6-8 new potential referral partners from outside their own chapter.",
      "The impact is multiplicative. When your 121 partner knows members in five other chapters, your effective referral network expands from 35 to 200+ in a single event. Members have reported receiving referrals from cross-chapter contacts months after attending a single conclave.",
      "BNI Miracles partners with chapters in Adyar, Anna Nagar, Velachery, and other Chennai zones. We host or co-host at least one conclave per quarter, rotating the venue across member businesses.",
    ],
  },
  {
    tamilName: "கல்லா கட்டுமா?",
    englishName: "Business Building",
    description: "Structured sessions and workshops to help members actively grow their businesses using BNI tools and strategies.",
    slug: "business-building",
    icon: "💼",
    fullDescription: [
      "BNI membership is a tool. கல்லா கட்டுமா? is about using that tool to its maximum potential. This initiative runs structured, practical sessions designed to help members extract real business value from their BNI membership.",
      "Sessions cover topics like: how to craft a compelling 60-second infomercial, how to ask for the right referral, how to convert a visitor into a member, and how to run effective 1-2-1 meetings. These are skills that compound over time.",
      "We also bring in external business coaches and successful BNI members from other chapters to share what has worked for them. Real stories, real numbers, real tactics.",
      "Members who actively engage with the business-building sessions consistently outperform in referrals passed and TYFCB generated. The investment is a few hours per quarter; the return is measured in lakhs.",
    ],
  },
  {
    tamilName: "யாரு சாமி அது?",
    englishName: "Know Your Member",
    description: "Deep-dive spotlights where members truly get to know each other's businesses, strengths, and ideal referrals.",
    slug: "know-your-member",
    icon: "🔍",
    fullDescription: [
      "You can only refer what you understand. யாரு சாமி அது? is our deep-dive initiative where one member per session gets a full spotlight — going far beyond the weekly 60-second infomercial.",
      "In a Know Your Member session, the featured member gets 20-30 minutes to walk the chapter through their business: what they do, who their best clients are, what a perfect referral looks like, and what makes their business unique.",
      "Members ask questions. They probe, they challenge, they engage. By the end of the session, every person in the room knows exactly who to call when they encounter someone who needs that business.",
      "The results are immediate and measurable. Members consistently report a spike in referrals in the week following their KYM spotlight. When your chapter truly knows your business, they become an extended sales force.",
    ],
  },
  {
    tamilName: "ஒரு ஆள் ஒரு Referral",
    englishName: "One Person One Referral",
    description: "A chapter-wide commitment: every single member passes at least one referral this week.",
    slug: "one-referral",
    icon: "🎯",
    fullDescription: [
      "The power of collective action. ஒரு ஆள் ஒரு Referral is a chapter-wide challenge where every single member — from the newest to the most veteran — commits to passing at least one referral in a specific week.",
      "When 35 members each pass one referral, the chapter processes 35 referrals in a single week. That's 35 potential new businesses, 35 warm introductions, 35 opportunities for members to demonstrate the value of BNI.",
      "The initiative creates friendly accountability. Members check in with each other during the week, share leads they've identified, and celebrate together when the target is met. It builds chapter momentum.",
      "Past One-Referral weeks have produced some of the highest referral counts in BNI Miracles history. More importantly, they've demonstrated to newer members that referral-passing is a habit anyone can build — it starts with one.",
    ],
  },
  {
    tamilName: "கற்போம் வெல்வோம்",
    englishName: "CEUs (Continuing Education)",
    description: "Learning sessions, BNI education slots, and external training to sharpen every member's business skills.",
    slug: "ceus",
    icon: "📚",
    fullDescription: [
      "Winners never stop learning. கற்போம் வெல்வோம் is BNI Miracles' commitment to the continuous education and professional growth of every member.",
      "Every BNI meeting includes an Education Coordinator slot — a short, powerful lesson on networking, business, or BNI principles. Our Education Coordinators go beyond the standard BNI curriculum to bring in fresh, locally relevant content.",
      "Beyond the weekly slot, we organise quarterly learning days featuring external speakers: marketing experts, chartered accountants, technology leaders, and business coaches. These full-day or half-day sessions are open to all members and sometimes to the public.",
      "Members have learned skills from digital marketing to export procedures, from personal branding to financial planning. The goal is for every BNI Miracles member to leave each year sharper, better-connected, and more confident than they entered it.",
    ],
  },
];
